CLASS ltcl_test DEFINITION FOR TESTING RISK LEVEL HARMLESS DURATION MEDIUM FINAL.
  PUBLIC SECTION.
    METHODS test_enqueue_dequeue FOR TESTING.
ENDCLASS.

CLASS ltcl_test IMPLEMENTATION.

  METHOD test_enqueue_dequeue.
    WRITE / 'todo'.
  ENDMETHOD.

ENDCLASS.