CLASS ltcl_test_key DEFINITION FOR TESTING RISK LEVEL HARMLESS DURATION MEDIUM FINAL.
  PUBLIC SECTION.
    METHODS test1 FOR TESTING RAISING cx_static_check.
ENDCLASS.

CLASS ltcl_test_key IMPLEMENTATION.
  METHOD test1.

  ENDMETHOD.
ENDCLASS.