name: test

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
    - run: npm run docker:start
    - run: docker network ls
    - run: npm install
    - run: npm test